version: "3.8"

services:
  nginx:
    image: nginx:latest
    ports:
      # - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./conf.d:/etc/nginx/conf.d
      - /etc/letsencrypt/live/keycloak.watchvaultbydiggie.com/fullchain.pem:/etc/nginx/ssl/fullchain.pem
      - /etc/letsencrypt/live/keycloak.watchvaultbydiggie.com/privkey.pem:/etc/nginx/ssl/privkey.pem
  keycloak:
    image: quay.io/keycloak/keycloak:24.0.4
    container_name: keycloak
    ports:
      - "8080:8080"
    environment:
      - KEYCLOAK_ADMIN=admin
      - KEYCLOAK_ADMIN_PASSWORD=admin
    command:
      - start-dev
